name: PR Validation Gatekeeper

on:
  pull_request:
    branches: [ "main" ]

# Cancel in-progress runs if new commits are pushed to the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/linting

  trivy-scan:
    name: Trivy Security Scan High and Critical
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/trivy-scan

  codeql-analysis:
    name: CodeQL C/C++ Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for CodeQL
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/codeql-analysis